### ISSUE TITLE
OpenOCD connection error Arty 35t board

### ISSUE THREAD

**Issue by sreeharshaangara** [platformio/platform-shakti#10]
Hi, 

I'm trying to do a simple hello world UART example using VSCode and PlatformIO. I have the Arty 35t board setup correctly with the E-Class bit file. I am running VSCode on Windows 10 and have the Shakti SDK installed.

When I try to run the Upload(either with the VSCode task or CLI), I run into an error with, 

```
Error: failed read at 0x16, status=2
Error: failed write at 0x16, status=1
Error: failed write at 0x17, status=2
Error: Fatal: Failed to read MISA from hart 0.
Error: Target not examined yet
```
Any clues? 

Also attaching full log here.
[OpenOCD_error_log.txt](https://github.com/platformio/platform-shakti/files/5180558/OpenOCD_error_log.txt)

**Comment by johnnavaj** [comment]
Hi,

The tool-openocd-riscv uses the sifive openocd  needs a update to the RTL since its missing one bit in the TAP specification.

So could you please try the building the openocd from this [commit](https://github.com/riscv/riscv-openocd/commit/fd9c54b1feea13f6846c69fc9e1e8dc3a7879717), the binary generated from this commit can be replaced with the openocd in tool-openocd-riscv used in your machine.


There will be a update to the RTL and the PIO framework soon with new updates and a fix for this too.

**Comment by sreeharshaangara** [comment]
Thank @johnnavaj, I'll give it a shot.

Do you have the compile options you usually use for a Windows 64-bit compile for OpenOCD when your invoke the ./configure script?

**Comment by johnnavaj** [comment]
Oh windows is ming32 gnu so you should pass something like this ./configure --host=i686-w64-mingw32 or 64 along with --enable-ftdi for enabling ftdi.

I strongly suggest you run PIO on ubuntu instead to avoid inconsistencies.

**Comment by johnnavaj** [comment]
@sreeharshaangara Please try the latest commit, E Class points to Pinaka SOC (Added in latest commit). This should fix this. If all goes well you can close this issue. Thanks.

**Comment by sreeharshaangara** [comment]
@johnnavaj sorry for the delay, I did a PIO update to 1.1.0 but the error persists. 

When I look into the .platformio\packages\tool-openocd-riscv package; that still shows the old OpenOCD(so no update). Do I need to manually update this tool? I looked through the previous comment but it only points to a Linux OpenOCD binary, no Windows

**Comment by johnnavaj** [comment]
@sreeharshaangara Can you please tell me which soc repo are you using ?
 Please Update in PIO for the SDK files in the VSCode , the OpenOCD remains the same ( Sifive commit) , it only changes in SOC and SDK files.

**Comment by bil-ash** [comment]
@sreeharshaangara Any updates?

**Comment by sreeharshaangara** [comment]
@johnnavaj my understanding was that this is a OpenOCD issue from the post in September 6
"The tool-openocd-riscv uses the sifive openocd needs a update to the RTL since its missing one bit in the TAP specification."

@bil-ash  
I've updated everything I could with 
PlatformIO is 5.0.3 
Shakthi Platform is 1.1.0 

I'm trying to run the example from the repository here, https://github.com/platformio/platform-shakti/tree/develop/examples 

And I get the same error as my original post.

**Comment by johnnavaj** [comment]
@sreeharshaangara i guess you are still using the old bitstream from the [shakti-soc](https://gitlab.com/shaktiproject/cores/shakti-soc) , please use the bitstream from [here]( https://gitlab.com/shaktiproject/sp2020/-/tree/master/e32-a35) , if you have updated the PIO keep it as it is since its 1.1.0 now . Please update your SOC since the TAP has changed as i mentioned earlier that its missing one bit.

**Comment by sreeharshaangara** [comment]
Ah, I see. Yes I haven't updated the bitstream file for the SoC itself. I'll give that a shot

**Comment by sreeharshaangara** [comment]
@johnnavaj any chance you guys are providing a pre-built MCS file for testing? Re-building is a real pain in Windows-land

**Comment by johnnavaj** [comment]
@sreeharshaangara yes its there in the mcs folder in that link itself at master tree [here](https://gitlab.com/shaktiproject/sp2020/-/tree/master/mcs)

**Comment by sreeharshaangara** [comment]
Fantastic, thank you. I'll give it a shot in a couple of days

**Comment by sreeharshaangara** [comment]
Confirming that I'm able to program the chip now with the latest bit file and PIO 

Thanks for all the support guys, closing
